import json, pathlib
ROOT=pathlib.Path(__file__).parent
# Original, code-authored pixel mascots. Every silhouette and palette is game-specific.
ART={
'pip':['....ww....ww....','...wwww..wwww...','...wwww..wwww...','....wwwwwwww....','...wwwwwwwwww...','..wwwwwwwwwwww..','..wwkkwwwwkkww..','..wwkwwwwwwkww..','...wwwwppwwww...','....wwwwwwww....','..rrrrrrrrrrrr..','.rr..bbbbbb..rr.','.....bbbbbb.....','....bbbbbbbb....','....yy....yy....','...yyyy..yyyy...'],
'moxie':['..aa........aa..','.aaaa......aaaa.','..aappppppppaa..','...pppppppppp...','..pppppppppppp..','.ppwwkppppkwwpp.','.ppwwkppppkwwpp.','..pppppppppppp..','...ppppkkpppp...','....pppppppp....','...tttttttttt...','..tttwwwwwwttt..','..tttwrrrrwttt..','...ttwrrrrwtt...','....tt....tt....','...aaa....aaa...'],
'riff':['....ooo.........','...ooooo........','..ooooooo.......','.oooooooood.....','..oowkookwo.....','..oowkookwo.....','...ooooooo......','....ookoo.......','...cccccccc.....','..cccyyycccc....','..cccyyycccc....','...cccccccc.....','....dd..dd......','...ddd..ddd.....','.yyyyyyyyyyyyyy.','...kk......kk...'],
'pickup':['....yy....','...yyyy...','..yywwyy..','.yywwwyyy.','yyyyyyyyyy','.yyyyyyyy.','..yyyyyy..','...yyyy...','....yy....','..........'],
'hazard':['....rr....','..rrrrrr..','.rrrrrrrr.','rrwwrrwwrr','rrwkrrkwrr','rrrrrrrrrr','.rrkkkkrr.','..rrrrrr..','...r..r...','..........']}
PAL={'pip':{'w':'#fff0cd','k':'#252548','p':'#ffb0b0','r':'#f76486','b':'#58bddd','y':'#ffd57b'},'moxie':{'a':'#f67cb2','p':'#8ce7cf','k':'#182e52','w':'#fff9d7','t':'#8e80db','r':'#f87589'},'riff':{'o':'#ffb866','d':'#28204d','w':'#fff6db','k':'#221c40','c':'#71e8d2','y':'#ffe279'},'pickup':{'y':'#ffde79','w':'#fffbe6'},'hazard':{'r':'#de6997','w':'#f9eeff','k':'#382950'}}
def sprite(name):
    rows=ART[name]; alt=rows[:]
    if name in ('pip','moxie','riff'): alt[-3],alt[-2]=alt[-2],alt[-3]
    return {'palette':PAL[name],'frames':[rows,alt],'fps':6}
def rule(id,when,do,cond=None,**kw):
    d={'id':id,'when':when,'do':do,**kw}
    if cond:d['if']=cond
    return d
def burst(at,col,n=14):return {'burst':{'at':at,'n':n,'color':col,'speed':[35,95],'life':[.2,.55],'size':2}}
def sound(freq):return {'seconds':.22,'level':.38,'layers':[{'sine':freq,'decay':17,'attack':.003},{'sine':freq*1.5,'decay':20,'delay':.04,'gain':.45}]}
def music(kind):
    bpm,key,scale,seed=[(112,'F','pentatonic',72),(100,'D','dorian',131),(120,'E','minor_pentatonic',203)][kind]
    return {'theme':{'bpm':bpm,'bars':8,'key':key,'scale':scale,'seed':seed,'lufs':-23,'reverb':{'decay':1.1,'mix':.14},'instruments':{
      'lead':{'seconds':.35 if kind!=1 else .8,'level':.45,'layers':[{'sine':1,'decay':9 if kind!=1 else 4},{'sine':2,'gain':.22,'decay':12}]},
      'bass':{'seconds':.36,'level':.5,'layers':[{'sine':1,'attack':.008,'decay':6},{'sine':2,'gain':.12,'decay':8}]},
      'hat':{'seconds':.065,'level':.16,'layers':[{'noise':'hp 0.6','decay':60,'attack':.002}]},
      'kick':{'seconds':.18,'level':.35,'layers':[{'sine':1,'decay':22,'attack':.003}]}},'tracks':[
      {'inst':'lead','play':'pattern','pattern':['x.x. .xx. x.x. xx..','x... ..x. .x.. ..x.','x.xx ..x. x.x. .xx.'][kind],'notes':['1 3 5 8 5 3 2 5','1 5 9 8 6 5 3 2','1 3 5 7 5 3 1 8'][kind],'octave':5,'gain':.65},
      {'inst':'bass','play':'pattern','pattern':'x..x ..x. x..x ..x.','notes':['1 1 4 5','1 6 4 5','1 1 4 5'][kind],'octave':2,'gain':.85},
      {'inst':'hat','play':'pattern','pattern':'..x. ..x. ..x. ..x.','notes':'1','octave':4,'gain':.38},
      {'inst':'kick','play':'pattern','pattern':'x... .... x... ....','notes':'1','octave':2,'gain':.7}]}}
def base(id,title,desc,char,col,bg,kind):
    g={'game2d':1,'id':id,'title':title,'description':desc,'capabilities':{'presentation':'2d','platforms':['web'],'networking':'offline','input':['keyboard','mouse','touch','gamepad'],'persistence':['settings','progress']},'view':{'width':480,'height':270,'background':bg},'sprites':{x:sprite(x) for x in (char,'pickup','hazard')},'sounds':{'pick':sound(880),'boost':sound(440),'hit':sound(160),'perfect':sound(1320),'win':{'seconds':.7,'level':.4,'layers':[{'sine':523,'decay':7},{'sine':659,'delay':.12,'decay':7},{'sine':784,'delay':.24,'decay':7},{'sine':1046,'delay':.36,'decay':7}]}},'music':music(kind),'vars':{'score':0,'combo':0,'lives':3,'timeleft':45,'best':0,'best1':0,'best2':0,'player':1,'next_player':1,'rounds':0,'wins':0,'total':0,'rank':1,'last_score':0,'banked':0,'invuln':0},'persist':['best','best1','best2','next_player','rounds','wins','total','rank','last_score'],'prefabs':{},'scene':[],'ui':[],'rules':[],'checks':{'scenarios':[],'browser':[]}}
    g['prefabs'].update({'pickup':{'tag':'pickup','shape':{'sprite':'pickup','scale':2},'size':[18,18],'layer':3,'emit':{'rate':2,'life':[.2,.5],'speed':[3,9],'angle':[240,300],'color':col}},'hazard':{'tag':'hazard','shape':{'sprite':'hazard','scale':2},'size':[15,15],'layer':3},'decor':{'shape':{'rect':[36,2],'color':col},'layer':-1}})
    g['ui']=[{'panel':{'at':[0,0],'size':[480,42],'color':'#111627ee'}},{'text':title.upper(),'at':[12,7],'color':col,'scale':2},{'text':'P{player}   SCORE {score}   CHAIN {combo}   TIME {timeleft}','at':[12,29],'color':'#ffffff'}, {'text':'P1 BEST {best1}   P2 BEST {best2}   RANK {rank}','at':[12,254],'color':col}, {'bar':{'var':'lives','max':3,'at':[390,29],'size':[76,7],'color':'#ff86a0','back':'#41283f'}}, {'panel':{'at':[40,75],'size':[400,138],'color':'#111627f5'},'show':'ended'}, {'text':'ROUND COMPLETE!','at':[240,88],'align':'center','scale':2,'color':col,'show':'ended == 1'}, {'text':'ONE MORE TRY?','at':[240,88],'align':'center','scale':2,'color':'#ff86a0','show':'ended == 2'}, {'text':'P{player}: {last_score} POINTS   BEST {best}','at':[240,116],'align':'center','show':'ended'}, {'text':'PASS THE CONTROLLER TO P{next_player}','at':[240,135],'align':'center','color':col,'show':'ended'}, {'text':'AUTO-SAVED: {rounds} ROUNDS / {wins} WINS','at':[240,152],'align':'center','show':'ended'}, {'button':{'id':'again','label':'A / SPACE: NEXT TURN','at':[130,175],'size':[220,22],'key':'Enter','do':[{'restart':True}]},'show':'ended'}, {'button':{'id':'music','label':'MIX','at':[440,251],'size':[34,14],'key':'KeyM','do':[{'music':'toggle'}]}}]
    g['rules']=[rule('whose turn',{'start':True},[{'set':['player','next_player']}]),rule('restore turn',{'event':'loaded'},[{'set':['player','next_player']}]),rule('clock',{'every':1},[{'add':['timeleft',-1]}]),rule('hurt',{'touch':['player','hazard']},[{'add':['lives',-1]},{'set':['combo',0]},{'set':['invuln','time + 1.1']},{'destroy':'other'},{'play':'hit'},{'shake':4},burst('self','#ff86a0')],'time > invuln'),rule('no hearts',{'every':.05},[{'end':'lose'}],'lives <= 0'),rule('bank speed bonus',{'end':'any'},[{'set':['banked','score + (ended == 1)*(timeleft + lives*5)']}]),rule('save record',{'end':'any'},[{'set':['last_score','banked']},{'add':['rounds',1]},{'add':['total','banked']},{'set':['next_player','3-player']}]),rule('best overall',{'end':'any'},[{'set':['best','banked']}],'banked > best'),rule('best player one',{'end':'any'},[{'set':['best1','banked']}],'player == 1 && banked > best1'),rule('best player two',{'end':'any'},[{'set':['best2','banked']}],'player == 2 && banked > best2'),rule('rank up',{'end':'any'},[{'set':['rank','1 + (total >= 150) + (total >= 400) + (total >= 800) + (total >= 1500)']}]),rule('celebrate',{'end':'win'},[{'add':['wins',1]},{'play':'win'},burst([240,120],col,45)]),rule('next turn',{'press':'action'},[{'restart':True}],'ended'),rule('controller music',{'press':'pause'},[{'music':'toggle'}])]
    g['checks']['browser']=[{'name':'music setting survives reload','click':[454,258],'changes':['music_on'],'persists':['music_on']}]
    return g
def scenario(name,script,expect,smoke=False):return {'name':name,'seed':1,'max_seconds':65,'script':script,'expect':expect,'smoke':smoke}
def finish(g,threshold):
    g['rules'] += [rule('target reached',{'every':.05},[{'end':'win'}],f'score >= {threshold}'),rule('goal at bell',{'every':.05},[{'end':'win'}],f'timeleft <= 0 && score >= {threshold}'),rule('missed goal',{'every':.05},[{'end':'lose'}],f'timeleft <= 0 && score < {threshold}')]
    g['checks']['scenarios'] += [scenario('idle run ends and saves the next turn',[{'wait':46}],[{'ended':'lose'},{'var':'rounds','eq':1},{'var':'next_player','eq':2}]),scenario('controller restart alternates players and keeps progress',[{'wait':46},{'press':'action'},{'wait':.1}],[{'not_ended':True},{'var':'player','eq':2},{'var':'rounds','eq':1},{'var':'timeleft','eq':45}])]
    folder=ROOT/g['id'];folder.mkdir(exist_ok=True)
    (folder/(g['id']+'.game2d.json')).write_text(json.dumps(g,indent=2)+'\n')
# PIP: a continuous rebound rhythm, with a deliberate ground slam that supercharges the next spring.
g=base('pip-cloud-post','Pip Cloud Post','Pip the scarf-wearing cloud rabbit delivers sunshine! Steer each automatic bounce; A/Space slams down for a super spring. Catch 12 letters before 45 seconds. Fast wins earn bonus points. B toggles music. Three hearts. Pass after every round. Records, ranks and progress auto-save; backup on the start card.','pip','#ffde90','#203957',0)
g['vars'].update({'slam':0,'bounces':0,'boosts':0})
g['controls']={'layout':'lr','a':'SLAM','b':{'label':'MUSIC','action':'secondary'},'pause':False}
g['prefabs'].update({'player':{'tag':'player','shape':{'sprite':'pip','scale':2,'flip':'auto'},'size':[18,24],'layer':5,'clamp':True,'body':{'type':'dynamic','gravity':560,'max_fall':600},'collide':['floor'],'move':{'keys':{'mode':'platformer','speed':150,'jump':1}}},'floor':{'tag':'floor','shape':{'rect':[480,18],'color':'#96dbcb'},'body':{'type':'static'}},'cloud':{'shape':{'circle':26,'color':'#385474'},'layer':-2}})
g['prefabs']['hazard'].update({'move':{'drift':[-65,0]},'ttl':9})
g['scene']=[{'prefab':'floor','at':[240,243]},{'prefab':'player','at':[64,210],'id':'p'}]+[{'prefab':'cloud','at':[x,y]} for x,y in [(45,95),(150,75),(290,88),(410,64)]]+[{'prefab':'pickup','at':[x,155]} for x in [64,150,240,330,416]]
g['rules'] += [rule('slam',{'press':'action'},[{'set':['slam',1]},{'velocity':{'target':'id:p','v':[0,500]}},{'play':'boost'},burst('self','#ffbfa6')],'!ended && p_y < 218'),rule('super spring',{'every':.0166667},[{'velocity':{'target':'id:p','v':[0,-410]}},{'set':['slam',0]},{'add':['boosts',1]},{'add':['bounces',1]},{'play':'perfect'},{'shake':2},burst(["p_x",226],'#ffde90')],'p_y >= 222 && slam == 1'),rule('spring',{'every':.0166667},[{'velocity':{'target':'id:p','v':[0,-340]}},{'add':['bounces',1]},{'play':'boost'},burst(["p_x",228],'#96dbcb',6)],'p_y >= 222'),rule('letter delivery',{'touch':['player','pickup']},[{'add':['combo',1]},{'add':['score',1]},{'play':'pick'},burst('other','#ffde90'),{'destroy':'other'}]),rule('fresh letters',{'every':.7},[{'spawn':{'prefab':'pickup','at':{'x':[28,452],'y':[116,180]}}}],'count_pickup < 8'),rule('raincloud',{'every':6},[{'spawn':{'prefab':'hazard','at':[474,164]}}],'count_hazard < 3'),rule('B music',{'press':'secondary'},[{'music':'toggle'}])]
g['ui'].append({'text':'STEER: LEFT/RIGHT   A: SLAM + SUPER SPRING   GOAL: 12','at':[14,47],'color':'#c9e6f0'})
g['checks']['scenarios']=[scenario('automatic bounces collect a letter',[{'wait':1.6}],[{'var':'score','gte':1},{'var':'bounces','gte':1},{'sound':'pick'},{'not_ended':True}],True),scenario('slam charges a super spring',[{'wait':.3},{'press':'action'},{'wait':1}],[{'var':'boosts','gte':1},{'sound':'perfect'}]),scenario('a roaming courier can complete the delivery',[{'hold':['right'],'seconds':2.2},{'hold':['left'],'seconds':2.5}]*9,[{'ended':'win'},{'var':'score','gte':12},{'var':'wins','eq':1},{'var':'best1','gte':12}])]
g['checks']['browser'].append({'name':'steering moves Pip','keys':['ArrowRight'],'ms':450,'changes':['p_x']})
finish(g,12)
# MOXIE: directional snap dashes spawn a magnetic collection field. Chains reward moving between clusters.
g=base('moxie-magnet-moon','Moxie Magnet Moon','Moxie the axolotl salvager has a magnetic backpack! Move with the stick; A/Space snaps 58 pixels in your last direction and pulls all nearby stardust into a combo. Recharge between bursts, dodge dust bunnies, bank 30 points before 45 seconds. Fast wins earn bonus points. B skips a ready dash to fire a stationary pulse. Progress auto-saves.','moxie','#8ce7cf','#1c1c3a',1)
g['vars'].update({'dx':1,'dy':0,'ready':0,'pulses':0,'charge':1,'snapx':240,'snapy':150})
g['controls']={'layout':'stick','a':'SNAP','b':{'label':'PULSE','action':'secondary'},'pause':False}
g['prefabs'].update({'player':{'tag':'player','shape':{'sprite':'moxie','scale':2,'flip':'auto'},'size':[19,21],'layer':5,'clamp':True,'move':{'keys':{'mode':'topdown','speed':110}}},'pulse':{'tag':'pulse','shape':{'circle':43,'color':'#8ce7cf48'},'size':[86,86],'layer':2,'ttl':.12},'moon':{'shape':{'circle':26,'color':'#38304f'},'layer':-2}})
g['prefabs']['hazard'].update({'move':{'chase':{'target':'player','speed':23}}})
g['scene']=[{'prefab':'player','at':[240,150],'id':'p'},{'prefab':'hazard','at':[30,70]},{'prefab':'moon','at':[400,92]},{'prefab':'moon','at':[80,210]}]+[{'prefab':'pickup','at':[x,y]} for x,y in [(298,150),(318,136),(312,166),(140,100),(158,118),(120,114),(340,216),(360,204)]]
for a,dx,dy in [('left',-1,0),('right',1,0),('up',0,-1),('down',0,1)]:g['rules'].append(rule('aim '+a,{'press':a},[{'set':['dx',dx]},{'set':['dy',dy]}],'!ended'))
pulse=[{'spawn':{'prefab':'pulse','at':['p_x','p_y']}},{'set':['ready','time + .85']},{'add':['pulses',1]},{'play':'boost'},{'shake':2},burst(["p_x","p_y"],'#8ce7cf',20)]
g['rules'] += [rule('snap',{'press':'action'},[{'set':['snapx','(p_x + dx*58 >= 20 && p_x + dx*58 <= 460)*(p_x + dx*58) + (p_x + dx*58 < 20)*20 + (p_x + dx*58 > 460)*460']},{'set':['snapy','(p_y + dy*58 >= 74 && p_y + dy*58 <= 230)*(p_y + dy*58) + (p_y + dy*58 < 74)*74 + (p_y + dy*58 > 230)*230']},{'teleport':{'target':'id:p','to':['snapx','snapy']}},{'emit':'magnet'}],'!ended && time >= ready'),rule('snap field',{'event':'magnet'},[{'spawn':{'prefab':'pulse','at':['snapx','snapy']}},*pulse[1:]]),rule('pulse',{'press':'secondary'},pulse,'!ended && time >= ready'),rule('charge display',{'every':.05},[{'set':['charge','time >= ready']}]),rule('magnetic salvage',{'touch':['pulse','pickup']},[{'add':['combo',1]},{'add':['score','2 + (combo > 3)']},{'destroy':'other'},{'play':'pick'},burst('other','#8ce7cf')]),rule('hand salvage',{'touch':['player','pickup']},[{'add':['score',1]},{'destroy':'other'},{'play':'pick'}]),rule('combo expires',{'every':.1},[{'set':['combo',0]}],'time > ready + 1.8'),rule('dust appears',{'every':10},[{'spawn':{'prefab':'hazard','at':[20,64]}}],'count_hazard < 3'),rule('new scrap',{'every':.65},[{'spawn':{'prefab':'pickup','at':{'x':[36,444],'y':[74,231]}}}],'count_pickup < 18')]
g['ui'] += [{'text':'STICK: AIM + MOVE   A: SNAP   B: PULSE   GOAL: 30','at':[14,47],'color':'#c1c1ee'},{'bar':{'var':'charge','max':1,'at':[210,240],'size':[60,4],'color':'#8ce7cf','back':'#544369'}}]
g['checks']['scenarios']=[scenario('a snap magnetically collects the starting cluster',[{'press':'action'},{'wait':.15}],[{'var':'score','gte':6},{'var':'pulses','eq':1},{'var':'combo','gte':2},{'sound':'pick','min':2}],True),scenario('magnet has a real recharge',[{'press':'action'},{'wait':.1},{'press':'secondary'},{'wait':.1}],[{'var':'pulses','eq':1},{'var':'charge','eq':0}]),scenario('salvage route banks enough points',[{'approach':'pickup','seconds':35},{'wait':11}],[{'ended':'win'},{'var':'score','gte':30},{'var':'best1','gte':30},{'var':'wins','eq':1}])]
g['checks']['browser'].append({'name':'stick equivalent moves Moxie','keys':['ArrowRight'],'ms':450,'changes':['p_x']})
finish(g,30)
# RIFF: beat-synchronous air tricks, lane switching and moving note lines.
g=base('riff-rooftop-rush','Riff Rooftop Rush','Riff the roller-skating fox rides a neon rooftop mixtape. Up/down changes lanes. A/Space hops over grumps; taps near the 120 BPM beat earn PERFECT trick chains. Grab notes and reach 80 points before 45 seconds. Fast wins earn bonus points. B drops to the middle lane. Three hearts, alternating records and saved ranks.','riff','#ffe279','#241c3b',2)
g['vars'].update({'lane':1,'air_until':0,'air':0,'phase':0,'perfects':0,'wave':0})
g['controls']={'layout':'dpad','a':'HOP','b':{'label':'CENTER','action':'secondary'},'pause':False}
g['prefabs'].update({'player':{'tag':'player','shape':{'sprite':'riff','scale':2},'size':[18,18],'layer':5},'rail':{'shape':{'rect':[480,3],'color':'#564265'},'layer':-1},'window':{'shape':{'rect':[7,12],'color':'#58415b'},'layer':-2}})
g['prefabs']['pickup'].update({'move':{'drift':[-150,0]},'ttl':3.4})
g['prefabs']['hazard'].update({'move':{'drift':[-150,0]},'ttl':3.4})
g['scene']=[{'prefab':'player','at':[130,150],'id':'p'}]+[{'prefab':'rail','at':[240,y+13]} for y in [92,150,208]]+[{'prefab':'window','at':[x,65]} for x in range(20,480,25)]+[{'prefab':'pickup','at':[x,150]} for x in [230,300,370]]
# Airborne collisions do not cost a heart.
for r in g['rules']:
    if r['id']=='hurt':r['if']='time > invuln && air == 0'
g['rules'] += [rule('lane up',{'press':'up'},[{'add':['lane',-1]}],'!ended && lane > 0'),rule('lane down',{'press':'down'},[{'add':['lane',1]}],'!ended && lane < 2'),rule('center',{'press':'secondary'},[{'set':['lane',1]}],'!ended'),rule('phase',{'every':.0166667},[{'set':['phase','time % 0.5']},{'set':['air','time < air_until']},{'teleport':{'target':'id:p','to':[130,'92 + lane*58 - air*27']}}]),rule('perfect trick',{'press':'action'},[{'add':['perfects',1]},{'add':['combo',1]},{'add':['score','2 + (combo > 4)']},{'set':['air_until','time + .36']},{'set':['invuln','time + .36']},{'play':'perfect'},burst([130,'p_y'],'#ffe279')],'!ended && time >= air_until && (time % 0.5 < 0.11 || time % 0.5 > 0.39)'),rule('offbeat hop',{'press':'action'},[{'set':['air_until','time + .30']},{'set':['invuln','time + .30']},{'play':'boost'},{'set':['combo',0]}],'!ended && time >= air_until'),rule('note',{'touch':['player','pickup']},[{'add':['score',5]},{'play':'pick'},{'destroy':'other'},burst('other','#71e8d2')]),rule('note stream',{'every':.65},[{'add':['wave',1]},{'spawn':{'prefab':'pickup','at':[476,'92 + (wave % 3)*58']}}]),rule('rooftop grump',{'every':2.4},[{'spawn':{'prefab':'hazard','at':[476,'92 + ((wave + 1) % 3)*58']}}])]
g['ui'] += [{'text':'UP/DOWN: LANES   A: HOP ON THE BEAT   GOAL: 80','at':[14,47],'color':'#d9cae7'},{'bar':{'var':'phase','max':.5,'at':[180,234],'size':[120,6],'color':'#ffe279','back':'#544369'}},{'text':'PERFECT!','at':[355,234],'color':'#ffe279','show':'combo > 0 && time < air_until'},{'text':'BEAT','at':[145,234],'color':'#ffe279'}]
g['checks']['scenarios']=[scenario('an on-beat hop scores a perfect',[{'wait':.5},{'press':'action'},{'wait':.1}],[{'var':'perfects','eq':1},{'var':'score','gte':2},{'var':'air','eq':1},{'sound':'perfect'}],True),scenario('offbeat hops clear hazards without perfect points',[{'wait':.24},{'press':'action'},{'wait':.08}],[{'var':'perfects','eq':0},{'var':'air','eq':1},{'sound':'boost'}]),scenario('lane switching stays on the three rails',[{'press':'up'},{'wait':.05},{'press':'up'},{'wait':.05}],[{'var':'lane','eq':0},{'entity':'p','near':[130,92],'tol':1}]),scenario('a rhythmic rooftop run reaches the goal',sum(([{'wait':.5 if i==0 else .46666667},{'press':'action'}] for i in range(18)),[])+[{'wait_until':{'ended':'win'},'timeout':12}],[{'ended':'win'},{'var':'score','gte':80},{'var':'wins','eq':1}])]
g['checks']['browser'].append({'name':'lane input moves Riff','keys':['ArrowUp'],'ms':150,'changes':['p_y']})
finish(g,80)
print('Built three original game definitions')
