#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]
use std::{env, fs, io::{Read, Write}, net::{TcpListener,TcpStream}, path::{Path,PathBuf}, process::Command, sync::{Arc,Mutex}, thread, time::{Duration,Instant}};
include!("game_config.rs");
fn mime(p:&str)->&'static str { match p.rsplit('.').next().unwrap_or(""){"html"=>"text/html; charset=utf-8","js"=>"text/javascript; charset=utf-8","json"|"webmanifest"=>"application/json","wasm"=>"application/wasm","png"=>"image/png","wav"=>"audio/wav",_=>"application/octet-stream"} }
fn response(s:&mut TcpStream,status:&str,kind:&str,body:&[u8]) { let h=format!("HTTP/1.1 {status}\r\nContent-Type: {kind}\r\nContent-Length: {}\r\nCache-Control: no-cache\r\nConnection: close\r\nX-Content-Type-Options: nosniff\r\n\r\n",body.len());let _=s.write_all(h.as_bytes());let _=s.write_all(body); }
fn handle(mut s:TcpStream,active:Arc<Mutex<Instant>>) { let _=s.set_read_timeout(Some(Duration::from_secs(3)));let _=s.set_write_timeout(Some(Duration::from_secs(10)));let mut b=[0u8;8192];let n=match s.read(&mut b){Ok(n)=>n,Err(_)=>return};let request=String::from_utf8_lossy(&b[..n]);let mut first=request.lines().next().unwrap_or("").split_whitespace();if first.next()!=Some("GET"){response(&mut s,"405 Method Not Allowed","text/plain",b"GET only");return}let url=first.next().unwrap_or("").split('?').next().unwrap_or("");
 if url=="/__arcade_health" || url=="/__arcade_ping"{*active.lock().unwrap()=Instant::now();response(&mut s,"200 OK","text/plain",ID.as_bytes());return}
 if url.contains('%')||url.contains("..")||url.contains('\\'){response(&mut s,"400 Bad Request","text/plain",b"Invalid path");return}
 let path=if url=="/"{"index.html"}else{url.trim_start_matches('/')};if let Some((_,data))=FILES.iter().find(|(p,_)|*p==path){*active.lock().unwrap()=Instant::now();response(&mut s,"200 OK",mime(path),data)}else{response(&mut s,"404 Not Found","text/plain",b"No such game file")}
}
fn serve()->Result<(),String>{let listener=TcpListener::bind(("127.0.0.1",PORT)).map_err(|e|format!("Cannot open this game's local port {PORT}: {e}"))?;listener.set_nonblocking(true).map_err(|e|e.to_string())?;let active=Arc::new(Mutex::new(Instant::now()));loop{match listener.accept(){Ok((s,_))=>{let a=active.clone();thread::spawn(move||handle(s,a));},Err(e)if e.kind()==std::io::ErrorKind::WouldBlock=>thread::sleep(Duration::from_millis(30)),Err(e)=>return Err(e.to_string())}if active.lock().unwrap().elapsed()>Duration::from_secs(90){break}}Ok(())}
fn existing_server()->bool{let mut s=match TcpStream::connect_timeout(&format!("127.0.0.1:{PORT}").parse().unwrap(),Duration::from_millis(200)){Ok(s)=>s,Err(_)=>return false};let _=s.set_read_timeout(Some(Duration::from_secs(1)));let _=s.write_all(b"GET /__arcade_health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n");let mut r=String::new();s.read_to_string(&mut r).is_ok()&&r.ends_with(ID)}
fn ps_quote(p:&str)->String{format!("'{}'",p.replace('\'',"''"))}
#[cfg(windows)]fn powershell(script:&str)->Result<(),String>{use std::os::windows::process::CommandExt;let result=Command::new("powershell.exe").args(["-NoProfile","-NonInteractive","-Command",script]).creation_flags(0x08000000).output().map_err(|e|e.to_string())?;if result.status.success(){Ok(())}else{Err(String::from_utf8_lossy(&result.stderr).into_owned())}}
#[cfg(windows)]fn shortcuts(root:&Path)->Result<(),String>{let exe=ps_quote(&root.join("play.exe").to_string_lossy());let folder=ps_quote(&root.to_string_lossy());let name=ps_quote(TITLE);let uninstall=ps_quote(&root.join("uninstall.ps1").to_string_lossy());let script=format!(r#"$ErrorActionPreference='Stop';$w=New-Object -ComObject WScript.Shell;$menu=Join-Path ([Environment]::GetFolderPath('StartMenu')) 'Programs\Red Engine Games';New-Item -ItemType Directory -Path $menu -Force|Out-Null;foreach($dir in @([Environment]::GetFolderPath('Desktop'),$menu)){{$s=$w.CreateShortcut((Join-Path $dir ({name}+'.lnk')));$s.TargetPath={exe};$s.WorkingDirectory={folder};$s.Save()}};$key='HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\RedEngineGames-{ID}';New-Item $key -Force|Out-Null;New-ItemProperty $key DisplayName -Value {name} -Force|Out-Null;New-ItemProperty $key DisplayVersion -Value '2.0' -Force|Out-Null;New-ItemProperty $key Publisher -Value 'Red Engine Games' -Force|Out-Null;New-ItemProperty $key InstallLocation -Value {folder} -Force|Out-Null;New-ItemProperty $key UninstallString -Value ('powershell.exe -NoProfile -ExecutionPolicy Bypass -File '+[char]34+{uninstall}+[char]34) -Force|Out-Null"#);powershell(&script)}
#[cfg(not(windows))]fn shortcuts(_:&Path)->Result<(),String>{Ok(())}
fn install(root:&Path,add_shortcuts:bool)->Result<(),String>{fs::create_dir_all(root.join("web")).map_err(|e|e.to_string())?;for(path,data)in FILES{let out=root.join("web").join(path);if let Some(d)=out.parent(){fs::create_dir_all(d).map_err(|e|e.to_string())?}fs::write(out,data).map_err(|e|e.to_string())?}let exe=env::current_exe().map_err(|e|e.to_string())?;let dest=root.join("play.exe");if exe!=dest{fs::copy(exe,&dest).map_err(|e|format!("Close the game before updating it: {e}"))?;}
 let uninstall=format!(r#"$ErrorActionPreference='Stop'
$root={}
Get-CimInstance Win32_Process | Where-Object {{ $_.ExecutablePath -eq (Join-Path $root 'play.exe') }} | ForEach-Object {{ Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }}
foreach($dir in @([Environment]::GetFolderPath('Desktop'),(Join-Path ([Environment]::GetFolderPath('StartMenu')) 'Programs\Red Engine Games'))) {{ Remove-Item (Join-Path $dir ({}+'.lnk')) -ErrorAction SilentlyContinue }}
Remove-Item 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\RedEngineGames-{}' -Recurse -ErrorAction SilentlyContinue
Remove-Item $root -Recurse -Force
# The separate browser profile is intentionally retained so reinstalling keeps progress.
"#,ps_quote(&root.to_string_lossy()),ps_quote(TITLE),ID);fs::write(root.join("uninstall.ps1"),uninstall).map_err(|e|e.to_string())?;if add_shortcuts{shortcuts(root)?}Ok(())}
#[cfg(windows)]fn launch(root:&Path)->Result<(),String>{use std::os::windows::process::CommandExt;let edge=["ProgramFiles(x86)","ProgramFiles","LOCALAPPDATA"].iter().filter_map(|v|env::var_os(v)).map(|p|PathBuf::from(p).join("Microsoft/Edge/Application/msedge.exe")).find(|p|p.exists()).ok_or("Microsoft Edge is required. Install Edge, then reopen the game.".to_string())?;
 if !existing_server(){Command::new(root.join("play.exe")).arg("--serve-only").creation_flags(0x08000000).spawn().map_err(|e|e.to_string())?;for _ in 0..60{if existing_server(){break}thread::sleep(Duration::from_millis(100));}if !existing_server(){return Err(format!("The game could not start on local port {PORT}. Close any other program using that port and try again."))}}
 let profile=PathBuf::from(env::var_os("LOCALAPPDATA").unwrap()).join("RedEngineGames/profiles").join(ID);Command::new(edge).arg(format!("--app=http://127.0.0.1:{PORT}/?desktop=1")).arg(format!("--user-data-dir={}",profile.display())).arg("--no-first-run").arg("--no-default-browser-check").spawn().map_err(|e|e.to_string())?;Ok(())}
#[cfg(not(windows))]fn launch(_:&Path)->Result<(),String>{Err("Use --serve-only to test on this platform".into())}
fn run()->Result<(),String>{let args:Vec<String>=env::args().collect();if args.iter().any(|a|a=="--serve-only"){return serve()}let custom=args.iter().position(|a|a=="--install-root").and_then(|i|args.get(i+1)).map(PathBuf::from);let root=custom.or_else(||env::var_os("LOCALAPPDATA").map(|p|PathBuf::from(p).join("RedEngineGames").join(ID))).ok_or("No LOCALAPPDATA or --install-root supplied".to_string())?;
 let current=env::current_exe().map_err(|e|e.to_string())?;if current!=root.join("play.exe") || !root.join("web/manifest.json").exists(){install(&root,!args.iter().any(|a|a=="--no-shortcuts"))?}if !args.iter().any(|a|a=="--no-launch"){launch(&root)?}Ok(())}
#[cfg(windows)]fn show_error(message:&str){#[link(name="user32")]extern "system"{fn MessageBoxW(h:*mut std::ffi::c_void,t:*const u16,c:*const u16,f:u32)->i32;}let t:Vec<u16>=message.encode_utf16().chain(Some(0)).collect();let c:Vec<u16>=TITLE.encode_utf16().chain(Some(0)).collect();unsafe{MessageBoxW(std::ptr::null_mut(),t.as_ptr(),c.as_ptr(),0x10);}}
#[cfg(not(windows))]fn show_error(message:&str){eprintln!("{message}")}
fn main(){if let Err(e)=run(){show_error(&e);std::process::exit(1)}}
